package emu.grasscutter.game.match;

public enum MatchSubType {
    MATCH_SUB_TYPE_HIDE,
    MATCH_SUB_TYPE_BOUNCE_CONJURING,
    MATCH_SUB_TYPE_ISLAND_PARTY,
    MATCH_SUB_TYPE_CHAR_AMUSEMENT,
    MATCH_SUB_TYPE_BRICK_BREAKER
}
